create table survey_2014_all_participants (
 dataid integer, 
 status character varying, 
 foundation_pier_beam character varying,
 foundation_slab character varying, 
 spend_time_at_home_monday character varying, 
 spend_time_at_home_tuesday character varying,
 spend_time_at_home_wednesday character varying,
 spend_time_at_home_thursday character varying,
 spend_time_at_home_friday character varying,
 ethnicity_asian_pacific_islander character varying,
 ethnicity_black_african_american character varying,
 ethnicity_caucasian_other_than_hispanic_or_latino character varying,
 ethnicity_hispanic_or_latino character varying,
 ethnicity_native_american_alaska_native character varying,
 ethnicity_other character varying,
 ethnicity_decline character varying,
 residents_under_5 character varying,
 residents_6_to_12 character varying,
 residents_13_to_18 character varying,
 residents_19_to_24 character varying,
 residents_25_to_34 character varying,
 residents_35_to_49 character varying, 
 residents_50_to_64 character varying,
 residents_65_and_older character varying,
 education_level  character varying,
 total_annual_income character varying,
 pv_system_own character varying,
 pv_system_size character varying,
 pv_system_reason character varying,
 pv_system_satisfied character varying,
 pv_system_features_liked character varying, 
 pv_system_features_for_improvement character varying,
 pv_system_features_surprising character varying,
 pv_system_common_questions character varying,
 pv_system_common_response character varying, 
 pv_system_common_surprises character varying,
 pv_neg_factors_too_expensive character varying,
 pv_neg_factors_uncertainty character varying,
 pv_neg_factors_ugly character varying,
 pv_neg_factors_resale_value_concerns character varying,
 pv_neg_factors_none character varying,
 pv_neg_factors_other character varying,
 pv_pos_factors_independence character varying,
 pv_pos_factors_no_emissions character varying, 
 pv_pos_rate_increase_protection character varying,
 pv_pos_factors_other character varying,
 pv_pos_factors_none character varying,
 pv_owner_response character varying,
 retrofits character varying, 
 retrofits_detail character varying, 
 irrigation_system character varying, 
 ceiling_fans_count character varying,
 hvac_central_air_gas_furnace character varying, 
 hvac_central_air_electric_furnace character varying,
 hvac_twoway_heat_pump character varying,
 hvac_geothermal_heat_pump character varying,
 hvac_window_ac character varying,
 hvac_ductless character varying,
 hvac_no_ac character varying,
 hvac_dont_know character varying,
 compressors_count character varying,
 compressor1_brand character varying,
 compressor1_year character varying,
 compressor1_model character varying, 
 compressor2_brand character varying,
 compressor2_year character varying,
 compressor2_model character varying,
 compressor3_brand character varying,
 compressor3_year character varying,
 compressor3_model character varying,
 temp_summer_weekday_workday character varying,
 temp_summer_weekday_morning character varying,
 temp_summer_weekday_evening character varying,
 temp_summer_sleeping_hours_hours character varying,
 temp_summer_weekend_hours character varying,
 temp_winter_weekday_workday character varying,
 temp_winter_weekday_morning character varying,
 temp_winter_weekday_evening character varying,
 temp_winter_sleeping_hours_hours character varying,
 temp_winter_weekend_hours character varying,
 thermostats_brand  character varying,
 programmable_thermostat_currently_programmed character varying, 
 programmable_thermostat_difficulty  character varying,
 ac_service_package  character varying,
 electronic_devices_cable_box_number character varying,
 electronic_devices_dvr_number character varying,
 electronic_devices_wifi_number character varying,
 electronic_devices_game_system_number character varying,
 electronic_devices_on_other character varying
);

\copy survey_2014_all_participants from '/usr/data/survey_2014_all_participants.csv' WITH CSV HEADER DELIMITER AS ';';


create table temp_participants (
 dataid character varying, 
 num_residents numeric
);


\copy temp_participants (dataid, num_residents) FROM '/usr/data/survey_2014_num_participants.csv' WITH CSV HEADER DELIMITER AS ',';